will-stone/browserosaurus

- package.json
#10 
When both modes are used:
The (very little) improment is that this way is (very little) more user friendly than with the zip files.
You also get ~2Mb for free.
You can also upload both of them on the release page.
> Added selective dmg/zip packaging

- src/main.js
Safari does not stay as the default browser across app rescan.
Ways to reproduce:
* Set Safari as default browser
* Hit "Rescan"
* Safari is not the default browser anymore
Extracted the same logic to filter out uninstalled app that find the ones available.
Safari has not appId and is automatically pruned by error without
> fix(): safari does not survive a rescan

- src/main.ts
Stop using About window (which is buggy) and just report version number in the tray menu. Also separate options, actions, and info by separators.
The by-product of this is that it fixes #103.
> feat: move version number to tray

- src/main/main.ts
Icon still appears in dock, but it hides right after window is closed.
#125
> fix(#125): Icon in dock doesn't hide

- docs/index.html
FAQ updated with the info, that Spotlight indexing for applications should be active.
for more see: https://github.com/will-stone/browserosaurus/issues/309#issuecomment-714449689
> updating FAQ with Spotlight indexing settings 

- src/config/logos.ts
Changed the bundle identifier to net.waterfox.waterfox (from net.waterfox.waterfoxcurrent)
Fixes #376
> Update waterfox bundle id

- package-lock.json
- package.json
- src/main/utils/get-app-icons.ts
Uses `electron-log` to log (in prouction) when `file-icon` is used to get an icon, and when it fails. Output logs will be stored in `~/Library/Logs/Browserosaurus`
> feat: add logging around getAppIcon

- src/config/apps.ts
Just add the [official Twitter app from macOS AppStore](https://apps.apple.com/jp/app/twitter/id1482454543?l=en&mt=12)
> feat: add official Twitter app from macOS AppStore

- src/config/apps.ts
I have tested Browserosaurus with Whist locally and it behaves as I'd expect.
> feat: add support for Whist browser

- src/config/apps.ts
Tor Browser and Safari Technology Preview
Fixes #599
> fix: fix names for two browsers

- src/config/apps.ts
Fixes the name of the Brave Beta browser 🙂
> fix: correct the name for the Brave Beta browser

- src/main/utils/get-installed-app-names.ts
This is a small fix to address #580 whereby permission errors resulted in an incomplete browser list. This fix suppresses find errors when scanning for supported applications.
> fix: suppress find errors

- src/renderers/prefs/components/organisms/pane-apps.tsx
Adds an instruction text to Apps pane in preferences fixing #620. I considered adding an icon before each app (some kind of touch target that indicates that the list items are sortable by dragging and dropping) but decided to keep the scope small.
> Add Drag and drop instructions to Apps pane in preferences

- package-lock.json
- src/main/utils/get-installed-app-names.ts
Fixes spinning circle in V. 20.x #629 
Might be a better way though.
> fix: skip error from shell script

- src/config/apps.ts
Option for pre-release supporters to include https://browser.kagi.com/updates/orion-release-notes.html
> feat: add Orion RC browser support

- src/main/utils/get-installed-app-names.ts
Not all applications are installed at `/Applications`.  Devices where privilege access is reduced can't install apps in the root applications folder, but can install them at `~/Applications`. This is a pretty standard directory across MacOS therefore can be added as an additional directory for the `find` command
fixes: https://github.com/will-stone/browserosaurus/issues/656
> feat: find applications in user home directory

- src/config/apps.ts
feat: add support for Opera Developer
> feat: add support for Opera Developer

- src/config/apps.ts
This PR allows Browserosaurus to open URLs with Microsoft Edge (along with its lesser stable release channels) in private mode.
Microsoft Edge is a decent choice on macOS, especially for someone like me who must also use Windows.
> feat: support InPrivate browsing in Microsoft Edge

- src/config/apps.ts
Chromium-Gost a open-source fork of chromium from russia 
Thorium browser private mode was not present
> feat: support InPrivate browsing in Thorium add Chromium-Gost support

- src/config/apps.ts
Microsoft renamed legacy teams and introduced a new version of teams with a new name. This will support all 3 app names, but you won't be able to choose between them with Browserosaurus, since they all use the same msteams:/ URL prefix.
> feat: add support for New and Classic Microsoft Teams

- src/config/apps.ts
Added support for Basilisk and Pale Moon
> Add support for Basilisk and Pale Moon

- src/config/apps.ts
Adds support for the PrivateWindow and PublicWindow browser apps from [https://github.com/lapcat/PrivateWindow](https://github.com/lapcat/PrivateWindow). I find these apps useful for explicitly opening a link in Safari using a Private window or a normal window.
> feat: add support for PrivateWindow and PublicWindow browser apps
